dataset:
  type: "OfficeDataset"
  args:
    root_dir: "/HDD4T/minhnt425/ot/kfot/data/office31"
    annotation_file: "/HDD4T/minhnt425/ot/kfot/data/office31/amazon.txt"

dataloader:
  batch_size: 32
  shuffle: false
  pin_memory: true
  num_workers: 3
