model:
  type: "timm.create_transform"
  args:
    model_name: 'resnet50' 
    pretrained: true
    num_classes: 0

transforms:
  Resize: 
    size: 235, 
    interpolation: "bicubic"
    max_size:
    antialias: true
  CenterCrop: 
    size: [224, 224]
  ToTensor: 
  Normalize: 
    mean: [0.4850, 0.4560, 0.4060]
    std: [0.2290, 0.2240, 0.2250]