num_epochs: 50
valid_freq: 10
loss:
  args: null
  type: torch.nn.CrossEntropyLoss
optimizer:
  args:
    lr: 1.0e-03
  type: torch.optim.Adam
scheduler:
  type: "torch.optim.lr_scheduler.StepLR"
  parameter:
    step_size: 10
    gamma: 0.7
dataloader:
  train:
    batch_size: 32
    num_workers: 3
    pin_memory: true
    shuffle: false
  eval:
    batch_size: 32
    num_workers: 3
    pin_memory: true
    shuffle: true